<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\BoardGameClub.Domain\BoardGameClub.Domain.csproj" />
    <ProjectReference Include="..\BoardGameClub.Shared\BoardGameClub.Shared.csproj" />
	<Folder Include="Features\Games\AddGame\" />
	<Folder Include="Features\Games\GetGames\" />
	<Folder Include="Features\Games\UpdateGame\" />
	<Folder Include="Features\Members\CreateMember\" />
	<Folder Include="Features\Members\GetMembers\" />
	<Folder Include="Features\Members\UpdateMember\" />
	<Folder Include="Features\Sessions\GetSessions\" />
	<Folder Include="Features\Sessions\UpdateSession\" />
	<Folder Include="Interfaces\" />
	<Folder Include="DTOs\" />
	<Folder Include="Common\" />
	<Folder Include="Validators\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="14.1.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
